/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StackRouteImport } from './routes/stack'
import { Route as NpfRouteImport } from './routes/npf'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GamesAwesomeWordRouteImport } from './routes/games/awesome-word'
import { Route as GalleryCategoryIdRouteImport } from './routes/gallery/$categoryId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const NpfRoute = NpfRouteImport.update({
  id: '/npf',
  path: '/npf',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const GamesAwesomeWordRoute = GamesAwesomeWordRouteImport.update({
  id: '/awesome-word',
  path: '/awesome-word',
  getParentRoute: () => GamesRoute,
} as any)
const GalleryCategoryIdRoute = GalleryCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => GalleryRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/npf': typeof NpfRoute
  '/stack': typeof StackRoute
  '/tools': typeof ToolsRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/gallery/$categoryId': typeof GalleryCategoryIdRoute
  '/games/awesome-word': typeof GamesAwesomeWordRoute
  '/gallery/': typeof GalleryIndexRoute
  '/games/': typeof GamesIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/npf': typeof NpfRoute
  '/stack': typeof StackRoute
  '/tools': typeof ToolsRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/gallery/$categoryId': typeof GalleryCategoryIdRoute
  '/games/awesome-word': typeof GamesAwesomeWordRoute
  '/gallery': typeof GalleryIndexRoute
  '/games': typeof GamesIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/npf': typeof NpfRoute
  '/stack': typeof StackRoute
  '/tools': typeof ToolsRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/gallery/$categoryId': typeof GalleryCategoryIdRoute
  '/games/awesome-word': typeof GamesAwesomeWordRoute
  '/gallery/': typeof GalleryIndexRoute
  '/games/': typeof GamesIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gallery'
    | '/games'
    | '/npf'
    | '/stack'
    | '/tools'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/gallery/$categoryId'
    | '/games/awesome-word'
    | '/gallery/'
    | '/games/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/npf'
    | '/stack'
    | '/tools'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/gallery/$categoryId'
    | '/games/awesome-word'
    | '/gallery'
    | '/games'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gallery'
    | '/games'
    | '/npf'
    | '/stack'
    | '/tools'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/gallery/$categoryId'
    | '/games/awesome-word'
    | '/gallery/'
    | '/games/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  GamesRoute: typeof GamesRouteWithChildren
  NpfRoute: typeof NpfRoute
  StackRoute: typeof StackRoute
  ToolsRoute: typeof ToolsRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npf': {
      id: '/npf'
      path: '/npf'
      fullPath: '/npf'
      preLoaderRoute: typeof NpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/games/awesome-word': {
      id: '/games/awesome-word'
      path: '/awesome-word'
      fullPath: '/games/awesome-word'
      preLoaderRoute: typeof GamesAwesomeWordRouteImport
      parentRoute: typeof GamesRoute
    }
    '/gallery/$categoryId': {
      id: '/gallery/$categoryId'
      path: '/$categoryId'
      fullPath: '/gallery/$categoryId'
      preLoaderRoute: typeof GalleryCategoryIdRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GalleryRouteChildren {
  GalleryCategoryIdRoute: typeof GalleryCategoryIdRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryCategoryIdRoute: GalleryCategoryIdRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface GamesRouteChildren {
  GamesAwesomeWordRoute: typeof GamesAwesomeWordRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesAwesomeWordRoute: GamesAwesomeWordRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GalleryRoute: GalleryRouteWithChildren,
  GamesRoute: GamesRouteWithChildren,
  NpfRoute: NpfRoute,
  StackRoute: StackRoute,
  ToolsRoute: ToolsRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
